defmodule RockcutApiWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :rockcut_api

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_rockcut_api_key",
    signing_salt: "X6jKrG1P",
    same_site: "Lax"
  ]

  # The app is JSON-only; only the dev LiveDashboard (router `/dev`, behind
  # `:dev_routes`) needs this socket, so prod doesn't mount it (D36-A, task 3997).
  if Application.compile_env(:rockcut_api, :dev_routes) do
    socket "/live", Phoenix.LiveView.Socket,
      websocket: [connect_info: [session: @session_options]],
      longpoll: [connect_info: [session: @session_options]]
  end

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :rockcut_api,
    gzip: not code_reloading?,
    only: RockcutApiWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :rockcut_api
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug CORSPlug,
    origin: &RockcutApiWeb.Endpoint.cors_origins/0,
    credentials: true,
    # X-Rockcut-Device marks a sign-in made on a paired tablet (D34 §3.3).
    headers: ["Authorization", "Content-Type", "Accept", "X-Rockcut-Device"]

  def cors_origins do
    Application.get_env(:rockcut_api, :cors_origins, [
      "http://localhost:5173",
      "http://localhost:5174"
    ])
  end

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug RockcutApiWeb.Router
end
