FROM hexpm/elixir:1.19.3-erlang-28.1.1-debian-bookworm-20260112-slim

RUN apt-get update -y && apt-get install -y build-essential git \
    && apt-get clean && rm -f /var/lib/apt/lists/*_*

RUN mix local.hex --force && mix local.rebar --force

WORKDIR /app

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod +x /docker-entrypoint.sh

ENV MIX_ENV=dev

ENTRYPOINT ["/docker-entrypoint.sh"]
